/* layout maneja toda la configuracion de estilos de la página */
import "./globals.css";
import { inter } from "./config/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
