/* layout maneja toda la configuracion de estilos de la página */
import "../css/globals.css";
import { inter } from "../config/fonts";

export const metadata = {
  title: "Fuddplan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
